
export const phoneData = [
    { name: "Vilayət Vəliyev", position: "Rektor", phone: "1001" },
    { name: "Nicat Əhmədov", position: "Rektorluq", phone: "1011" },
    { name: "Gülşən Zilfiqarova", position: "Rektorluq", phone: "1000" },
    { name: "Nurəli Yusifbəyli", position: "Tədris işləri üzrə prorektor", phone: "1002" },
    { name: "Fərid Hüseynli", position: "Tədris işləri üzrə prorektorun köməkçisi", phone: "1012" },
    { name: "Sübhan Namazov", position: "Elm və innovasiya üzrə prorektor", phone: "1003" },
    { name: "Rüxsarə Mirzəyeva", position: "Elm və innovasiya üzrə prorektorun köməkçisi", phone: "1013" },
    { name: "Fariz Məmmədov", position: "Beynəlxalq əlaqələr üzrə prorektor", phone: "1004" },
    { name: "Şəbnəm Hətəmova", position: "Beynəlxalq əlaqələr üzrə prorektorun köməkçisi", phone: "1014" },
    { name: "Rəşad Əliyev", position: "Maliyyə-təsərrüfat işləri üzrə prorektor", phone: "1005" },
    { name: "Aysun Hüseynova", position: "Maliyyə-təsərrüfat işləri üzrə prorektorun köməkçisi", phone: "1015" },
    { name: "Nərmin Rzayeva", position: "Sosial məsələlər və ictimaiyyətlə əlaqələr üzrə prorektor", phone: "1006" },
    { name: "Kəmalə Mürşüdova", position: "Sosial məsələlər və ictimaiyyətlə əlaqələr üzrə prorektorun köməkçisi", phone: "1016" },
    { name: "Fariz Mustafayev", position: "Ümumi işlər üzrə prorektor", phone: "1007" },
    { name: "Yeganə Nəzərova", position: "Ümumi işlər üzrə prorektorun köməkçisi", phone: "1017" },
    { name: "Sevinc İsgəndərova", position: "Mətbuat katibi", phone: "1020" },
    { name: "Elvin Bəxtiyarlı", position: "Həmkarlar İttifaqı Komitəsinin sədri", phone: "3400" },
    { name: "Aynurə İsmayılova", position: "Universitet-sənaye əməkdaşlığı və ömürboyu təhsil mərkəzi müdiri", phone: "3000" },
    { name: "İnam Həsənov", position: "İKT şöbəsinin direktoru", phone: "1300" },
    { name: "Aytən Şıxaliyeva", position: "İnsan resursları departamentinin müdiri", phone: "1100" },
    { name: "Samir Musayev", position: "Maliyyə və təminat departamentinin müdiri", phone: "3300" },
    { name: "Amid Zəkiyev", position: "Maliyyə və təminat şöbəsinin müdiri", phone: "3304" },
    { name: "Asif Həmzətov", position: "Satınalma və təminat şöbəsinin müdiri", phone: "3305" },
    { name: "", position: "İKT şöbəsi", phone: "1301" },
    { name: "Rəna Hətəmova", position: "İnsan resursları şöbəsinin müdiri", phone: "1101" },
    { name: "Tahir Dadaşov", position: "Mühasibatlıq", phone: "3301" },
    { name: "Cavharat Dinavasova", position: "Strateji inkişaf mərkəzinin planlaşdırılması üzrə mütəxəssisi", phone: "1051" },
    { name: "Bəxtiyar Bədəlov", position: "Tədqiqat və inkişaf şöbəsinin müdiri", phone: "1150" },
    { name: "Vəfa Rzayeva", position: "Elmi katib", phone: "1010" },
    { name: "Akif Fərruxov", position: "Rektorun müşaviri", phone: "1019" },
    { name: "Ülviyyə Əliyevə", position: "Ümumi şöbənin müdiri", phone: "1200" },
    { name: "Mirməhəmməd Ələkbərli", position: "Tələbə Həmkarlar İttifaqı Komitəsinin sədri", phone: "3401" },
    { name: "Anar Eminov", position: "Yüksək Təhsil İnstitutu", phone: "3200" },
    { name: "Ülviyyə Rəsulova", position: "Karyera Mərkəzi", phone: "1130" },
    { name: "Qəmər İsayeva", position: "Sosial İnkişaf Mərkəzi", phone: "1120" },
    { name: "Fikrət Nəbiyev", position: "Kolleclər üzrə müşavir", phone: "1018" },
    { name: "Famil Qədimov", position: "Daxili infrastruktur sahələrinin əlaqələndirilməsi üzrə xüsusi nümayəndə", phone: "1021" },
    { name: "Ərəstun Məmmədov", position: "Tədris şöbəsinin müdiri", phone: "1500" },
    { name: "", position: "Ümumi Şöbə", phone: "1201" },
    { name: "", position: "Ümumi Şöbə", phone: "1202" },
    { name: "İlham Pirməmmədov", position: "Rektorun müşaviri", phone: "1022" },
    { name: "Səfa Bağırov", position: "Aztu tv müdiri", phone: "1160" },
    { name: "Osman Gündüz", position: "Rektorun rəqəmsal məsələlər üzrə məsləhətçisi", phone: "1009" },
    { name: "Yusif Novruzov", position: "Magistratura şöbə müdiri", phone: "3201" },
    { name: "", position: "Doktorantura", phone: "3202" },
    { name: "Anar Əliyev", position: "İmtahan mərkəzi müdir", phone: "2900" },
    { name: "Əfsanə Məmmədova", position: "İnsan Resursları", phone: "1102" },
    { name: "Səmayə Həsənova", position: "Strateji inkişaf şöbəsinin müdiri", phone: "1220" },
    { name: "Naib Hacıyev", position: "Müşavir", phone: "1008" },
    { name: "Naib Hacıyev", position: "Naib Mellim Köməkçi", phone: "1028" },
    { name: "Allahverdi Şərifov", position: "Nəqliyyat və logistika dekanı", phone: "2100" },
    { name: "Hüsenynqulu Quliyev", position: "Energetika və avtomatika dekanı", phone: "2200" },
    { name: "Razim Bayramov", position: "Nəqliyyat logistikası və hərəkətin təhlükəsizliyi kafedra müdiri", phone: "2110" },
    { name: "Qasım Manafov", position: "Nəqliyyat texnikası və idarəetmə texnologiyaları kafedra müdiri", phone: "2120" },
    { name: "Fuad Daşdəmirov", position: "Logistika və Nəqliyyat institutunun direktoru", phone: "2130" },
    { name: "Yadigar İmamverdiyev", position: "Kibertəhlükəsizlik kafedra müdiri", phone: "2640" },
    { name: "Atif Namazov", position: "Mühəndis riyaziyyatı və süni intellekt kafedra müdiri", phone: "2620" },
    { name: "Sevda Talişinskaya", position: "Qiyabi şöbə böyük mütəxəssis", phone: "2901" },
    { name: "Ceyhun Mahmudov", position: "Magistratura Program Mərkəzinin müdiri", phone: "3203" },
    { name: "Vidadi Mustafayev", position: "Əməyin mühafizəsi və texniki təhlükəsizlik şöbə müdiri", phone: "1170" },
    { name: "İsa Xəlilov", position: "Maşın dizaynı və sənaye texnologiyaları kafedra müdiri", phone: "2510" },
    { name: "Pərvanə Məmmədli", position: "Hüquqşünas", phone: "1900" },
    { name: "Pərvanə Mövsumova", position: "Keyfiyyət təminat şöbə müdiri", phone: "1140" },
    { name: "", position: "Mühavizə otagi(əsas giriş)", phone: "1391" },
    { name: "", position: "Mühavizə otagi(arxa giriş)", phone: "1392" },
    { name: "Səkinə Allahverdiyeva", position: "Tədris hissəsi (Koica)", phone: "1501" },
    { name: "Şərəfxanım Əliyeva", position: "Universitet-sənaye əməkdaşlığı və ömürboyu təhsil mərkəzi müdir müavini", phone: "3001" },
    { name: "Natavan Namazova", position: "İqtisadiyyat və statistika kafedra müdiri", phone: "2720" },
    { name: "Həbib Mirzəyev", position: "Humanitar fənlər kafedra müdiri", phone: "2710" },
    { name: "İlhamə Eyvazova", position: "Arxiv şöbə müdiri", phone: "1230" },
    { name: "Mülayim Osmanova", position: "Strateji inkişaf şöbəsi mütəxəssis", phone: "1221" },
    { name: "Cəfər Eyvazov", position: "Mühavizə rəisi", phone: "1390" },
    { name: "Mətanət Mehrabova", position: "Mühəndis fizikası və elektronika kafedra müdiri", phone: "2220" },
    { name: "Ramiz Kəlbiyev", position: "Enerji effektivliyi və yaşıl enerji texnologiyaları kafedra müdiri", phone: "2230" },
    { name: "Zəfər Cəfərov", position: "Kompüter texnologiyalar kafedra müdiri", phone: "2610" },
    { name: "Fərqanə Musayeva", position: "İqtisadiyyat və idarəetmə dekanı", phone: "2700" },
    { name: "Elçin Rzayev", position: "Xüsusi texnika və texnologiyaları dekanı", phone: "2300" },
    { name: "Aqil Babayev", position: "Metallurgiya və materiallar texnologiya kafedra müdiri", phone: "2420" },
    { name: "Fəxrəddin Yusubov", position: "Kimya texnologiya, təkrar emal və ekologiya kafedra müdiri", phone: "2410" },
    { name: "Nizami Poladov", position: "Metallurgiya və materialşünaslıq dekanı", phone: "2400" },
    { name: "Taleh Şirinov", position: "İnformasiya və telekommunikasiya texnologiyalar dekanı", phone: "2600" },
    { name: "Mehman Həsənov", position: "Radiotexnika və telekommunikasiya kafedra müdiri", phone: "2630" },
    { name: "Cavanşir Həsənov", position: "Əcnəbi tələbələrin qeydiyyatı üzrə mütəxəssis", phone: "1241" },
    { name: "", position: "İmtahan mərkəzi", phone: "2902" }
  ];

